# Generated by Django 5.1.1 on 2024-09-17 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('BILLBOARDS', 'BILLBOARDS'), ('TAXI', 'TAXI'), ('WEBSITE', 'WEBSITE'), ('CAMPAIGNS', 'CAMPAIGNS')], max_length=20, unique=True)),
                ('max_slots', models.PositiveIntegerField(default=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='staticfiles/ads/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('adCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.adcategory')),
            ],
        ),
    ]
